from typing import Callable, Optional

class IotCoreRs:
    """Native MQTT client. Use ``iotcore.IotCore`` instead."""

    def __init__(
        self,
        host: str,
        port: int,
        callback: Callable[[str, bytes], object],
        client_id: Optional[str] = None,
        keep_alive_secs: int = 5,
    ) -> None: ...
    @property
    def client_id(self) -> str: ...
    def publish(self, topic: str, payload: bytes, qos: int = 1, retain: bool = False) -> None: ...
    def subscribe(self, topic: str, qos: int = 0) -> None: ...
    def unsubscribe(self, topic: str) -> None: ...
    def disconnect(self) -> None: ...
    def begin_subscription(self) -> None: ...

class IotCoreBroker:
    """Native embedded broker. Use ``iotcore.Broker`` instead."""

    def __init__(
        self,
        config_path: Optional[str] = None,
        listen: str = "0.0.0.0",
        port: int = 1883,
        max_connections: int = 10_000,
        max_payload_size: int = 20_480,
        max_inflight_count: int = 100,
        connection_timeout_ms: int = 60_000,
    ) -> None: ...
    def listeners(self) -> list[str]: ...
    def check_ports(self) -> None: ...
    def run_forever(self) -> None: ...
    def start(self) -> None: ...
