# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('topic', models.CharField(max_length=180)),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 8, 13, 12, 21, 41, 770289, tzinfo=utc))),
            ],
        ),
    ]
