# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 12, 22, 36, 819432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mqtt',
            name='topic',
            field=models.CharField(default=' ', max_length=180),
        ),
    ]
