# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20160813_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
