# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20160829_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=500)),
                ('long', models.CharField(blank=True, max_length=500)),
                ('speed', models.CharField(blank=True, max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('deviceId', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
