# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_gps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gps',
            old_name='long',
            new_name='lng',
        ),
    ]
